### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by stbenjam** [stbenjam/go-imap-notmuch#2]
Seeing a crash like this every now and then:

```
2022-09-18T13:23:00.926548020Z | stderr | /app/vendor/github.com/emersion/go-imap/server/conn.go:111 +0x27f
-- | -- | --
2022-09-18T13:23:00.926519148Z | stderr | created by github.com/emersion/go-imap/server.newConn
2022-09-18T13:23:00.926490112Z | stderr | /app/vendor/github.com/emersion/go-imap/server/conn.go:217 +0xd7
2022-09-18T13:23:00.926460737Z | stderr | github.com/emersion/go-imap/server.(*conn).send(0xc000014f60)
2022-09-18T13:23:00.926433236Z | stderr | goroutine 139 [select, 2 minutes]:
2022-09-18T13:23:00.926410566Z | stderr |  
2022-09-18T13:23:00.926384448Z | stderr | /app/main.go:66 +0x1b1
2022-09-18T13:23:00.926358259Z | stderr | main.main()
2022-09-18T13:23:00.926309096Z | stderr | /app/vendor/github.com/emersion/go-imap/server/server.go:247 +0xb0
2022-09-18T13:23:00.926267927Z | stderr | github.com/emersion/go-imap/server.(*Server).ListenAndServe(0xc0000f80b0, 0xc0000bb210, 0xc0000baa00)
2022-09-18T13:23:00.926239116Z | stderr | /app/vendor/github.com/emersion/go-imap/server/server.go:216 +0x20e
2022-09-18T13:23:00.926209215Z | stderr | github.com/emersion/go-imap/server.(*Server).Serve(0xc0000f80b0, 0x7902c8, 0xc00000e3c0, 0x0, 0x0)
2022-09-18T13:23:00.926178982Z | stderr | /usr/lib/golang/src/net/tcpsock.go:261 +0x65
2022-09-18T13:23:00.926149710Z | stderr | net.(*TCPListener).Accept(0xc00000e3c0, 0x7453d8, 0xc0000f80b0, 0x793268, 0xc000014f60)
2022-09-18T13:23:00.926113418Z | stderr | /usr/lib/golang/src/net/tcpsock_posix.go:139 +0x32
2022-09-18T13:23:00.926081187Z | stderr | net.(*TCPListener).accept(0xc00000e3c0, 0xc001b85cc0, 0xc001b85cc8, 0x28)
2022-09-18T13:23:00.926053118Z | stderr | /usr/lib/golang/src/net/fd_unix.go:172 +0x45
2022-09-18T13:23:00.926024583Z | stderr | net.(*netFD).accept(0xc000f1c280, 0x6ab21f, 0x8, 0x7453e0)
2022-09-18T13:23:00.925995412Z | stderr | /usr/lib/golang/src/internal/poll/fd_unix.go:401 +0x212
2022-09-18T13:23:00.925963928Z | stderr | internal/poll.(*FD).Accept(0xc000f1c280, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
2022-09-18T13:23:00.925934771Z | stderr | /usr/lib/golang/src/internal/poll/fd_poll_runtime.go:92
2022-09-18T13:23:00.925904418Z | stderr | internal/poll.(*pollDesc).waitRead(...)
2022-09-18T13:23:00.925837638Z | stderr | /usr/lib/golang/src/internal/poll/fd_poll_runtime.go:87 +0x45
2022-09-18T13:23:00.925808307Z | stderr | internal/poll.(*pollDesc).wait(0xc000f1c298, 0x72, 0x0, 0x0, 0x7319e9)
2022-09-18T13:23:00.925779392Z | stderr | /usr/lib/golang/src/runtime/netpoll.go:227 +0x55
2022-09-18T13:23:00.925751367Z | stderr | internal/poll.runtime_pollWait(0x7f9a74413f18, 0x72, 0x0)
2022-09-18T13:23:00.925723440Z | stderr | goroutine 1 [IO wait, 2 minutes]:
2022-09-18T13:23:00.925700556Z | stderr |  
2022-09-18T13:23:00.925669674Z | stderr | /app/vendor/github.com/emersion/go-imap/server/server.go:228 +0x1f4
2022-09-18T13:23:00.925639670Z | stderr | created by github.com/emersion/go-imap/server.(*Server).Serve
2022-09-18T13:23:00.925607404Z | stderr | /usr/lib/golang/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc001b81fc0 sp=0xc001b81fb8 pc=0x470641
2022-09-18T13:23:00.925577767Z | stderr | runtime.goexit()
2022-09-18T13:23:00.925539977Z | stderr | /app/vendor/github.com/emersion/go-imap/server/server.go:280 +0xf4 fp=0xc001b81fb8 sp=0xc001b81f48 pc=0x6aeb34
2022-09-18T13:23:00.925509683Z | stderr | github.com/emersion/go-imap/server.(*Server).serveConn(0xc0000f80b0, 0x793268, 0xc000014f60, 0x0, 0x0)
2022-09-18T13:23:00.925476269Z | stderr | /app/vendor/github.com/emersion/go-imap/server/conn.go:346 +0x792 fp=0xc001b81f48 sp=0xc001b81e10 pc=0x6ad0f2
2022-09-18T13:23:00.925436472Z | stderr | github.com/emersion/go-imap/server.(*conn).serve(0xc000014f60, 0x793268, 0xc000014f60, 0x0, 0x0)
2022-09-18T13:23:00.925400415Z | stderr | /app/vendor/github.com/emersion/go-imap/server/conn.go:397 +0x9e fp=0xc001b81e10 sp=0xc001b81d90 pc=0x6ad5de
2022-09-18T13:23:00.925348853Z | stderr | github.com/emersion/go-imap/server.(*conn).handleCommand(0xc000014f60, 0xc001b81ed8, 0x4, 0x4, 0x0, 0x0, 0x0)
2022-09-18T13:23:00.925316023Z | stderr | /app/vendor/github.com/emersion/go-imap/server/cmd_selected.go:338 +0xc4 fp=0xc001b81d90 sp=0xc001b81d28 pc=0x6aae04
2022-09-18T13:23:00.925285659Z | stderr | github.com/emersion/go-imap/server.(*Uid).Handle(0xc0001e4bd0, 0x793268, 0xc000014f60, 0xc0001e4bd0, 0x0)
2022-09-18T13:23:00.925249712Z | stderr | /app/vendor/github.com/emersion/go-imap/server/cmd_selected.go:149 +0x45 fp=0xc001b81d28 sp=0xc001b81ce8 pc=0x6a9d65
2022-09-18T13:23:00.925217667Z | stderr | github.com/emersion/go-imap/server.(*Search).UidHandle(0xc00000e6d8, 0x793268, 0xc000014f60, 0x7f9a74235398, 0xc00000e6d8)
2022-09-18T13:23:00.925146036Z | stderr | /app/vendor/github.com/emersion/go-imap/server/cmd_selected.go:135 +0x6f fp=0xc001b81ce8 sp=0xc001b81c80 pc=0x6a9b8f
2022-09-18T13:23:00.925100184Z | stderr | github.com/emersion/go-imap/server.(*Search).handle(0xc00000e6d8, 0x411201, 0x793268, 0xc000014f60, 0xc00000e601, 0x7f9a74235398)
2022-09-18T13:23:00.925029597Z | stderr | /app/pkg/notmuch/mailbox.go:188 +0x605 fp=0xc001b81c80 sp=0xc001b81ad8 pc=0x695f45
2022-09-18T13:23:00.924994185Z | stderr | github.com/stbenjam/go-imap-notmuch/pkg/notmuch.(*Mailbox).SearchMessages(0xc0000ac320, 0xc0002bca01, 0xc0000c9e60, 0x9377f0, 0x0, 0x0, 0x0, 0x0)
2022-09-18T13:23:00.924962631Z | stderr | /app/vendor/github.com/zenhack/go.notmuch/db.go:41 +0x4e fp=0xc001b81ad8 sp=0xc001b81a98 pc=0x6850ee
2022-09-18T13:23:00.924933630Z | stderr | github.com/zenhack/go%2enotmuch.(*DB).Close(0xc0001d2a80, 0x1, 0x1)
2022-09-18T13:23:00.924900871Z | stderr | /app/vendor/github.com/zenhack/go.notmuch/cstruct.go:76 +0xb1 fp=0xc001b81a98 sp=0xc001b81a60 pc=0x683c31
2022-09-18T13:23:00.924866316Z | stderr | github.com/zenhack/go%2enotmuch.(*cStruct).doClose(0xc0001d2a80, 0xc001b81ab8, 0x0, 0x0)
2022-09-18T13:23:00.924835047Z | stderr | /app/vendor/github.com/zenhack/go.notmuch/db.go:42 +0x2a fp=0xc001b81a60 sp=0xc001b81a40 pc=0x686b2a
2022-09-18T13:23:00.924805735Z | stderr | github.com/zenhack/go%2enotmuch.(*DB).Close.func1(0xc0001d2a80, 0xc000000001)
2022-09-18T13:23:00.924766937Z | stderr | /app/vendor/github.com/zenhack/go.notmuch/db.go:42 +0x59 fp=0xc001b81a40 sp=0xc001b81a08 pc=0x686ad9
2022-09-18T13:23:00.924735158Z | stderr | github.com/zenhack/go%2enotmuch.(*DB).Close.func1.1(0xc0001d2a80, 0xc001b81a60)
2022-09-18T13:23:00.924703510Z | stderr | _cgo_gotypes.go:297 +0x45 fp=0xc001b81a08 sp=0xc001b819d8 pc=0x683f05
2022-09-18T13:23:00.924667228Z | stderr | github.com/zenhack/go%2enotmuch._Cfunc_notmuch_database_destroy(0x7f9a5d6846a0, 0xc000000000)
2022-09-18T13:23:00.924625966Z | stderr | /usr/lib/golang/src/runtime/cgocall.go:154 +0x5b fp=0xc001b819d8 sp=0xc001b819a0 pc=0x40933b
2022-09-18T13:23:00.924592640Z | stderr | runtime.cgocall(0x6b37f0, 0xc001b81a08, 0xc001b81a00)
2022-09-18T13:23:00.924562819Z | stderr | goroutine 140 [syscall]:
2022-09-18T13:23:00.924539314Z | stderr |  
2022-09-18T13:23:00.924507979Z | stderr | /usr/lib/golang/src/runtime/signal_unix.go:718 +0x2e5
2022-09-18T13:23:00.924477630Z | stderr | runtime.sigpanic()
2022-09-18T13:23:00.924390139Z | stderr | /usr/lib/golang/src/runtime/panic.go:1117 +0x72
2022-09-18T13:23:00.924359110Z | stderr | runtime.throw(0x73e84f, 0x2a)
2022-09-18T13:23:00.924331532Z | stderr | runtime stack:
2022-09-18T13:23:00.924304869Z | stderr |  
2022-09-18T13:23:00.924229717Z | stderr | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x0]
2022-09-18T13:23:00.562467797Z | stderr | fatal error: unexpected signal during runtime execution


```

**Comment by stbenjam** [comment]
```
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x7f0f2b7e037e]

runtime stack:
runtime.throw(0x73e84f, 0x2a)
	/usr/lib/golang/src/runtime/panic.go:1117 +0x72
runtime.sigpanic()
	/usr/lib/golang/src/runtime/signal_unix.go:718 +0x2e5

goroutine 25783 [syscall]:
runtime.cgocall(0x6b37f0, 0xc000123a08, 0x7f0f2af2b500)
	/usr/lib/golang/src/runtime/cgocall.go:154 +0x5b fp=0xc0001239d8 sp=0xc0001239a0 pc=0x40933b
github.com/zenhack/go%2enotmuch._Cfunc_notmuch_database_destroy(0x2c4ab80, 0xc000000000)
	_cgo_gotypes.go:297 +0x45 fp=0xc000123a08 sp=0xc0001239d8 pc=0x683f05
github.com/zenhack/go%2enotmuch.(*DB).Close.func1.1(0xc00613a090, 0xc000123a60)
	/app/vendor/github.com/zenhack/go.notmuch/db.go:42 +0x59 fp=0xc000123a40 sp=0xc000123a08 pc=0x686ad9
github.com/zenhack/go%2enotmuch.(*DB).Close.func1(0xc00613a090, 0xc005874501)
	/app/vendor/github.com/zenhack/go.notmuch/db.go:42 +0x2a fp=0xc000123a60 sp=0xc000123a40 pc=0x686b2a
github.com/zenhack/go%2enotmuch.(*cStruct).doClose(0xc00613a090, 0xc000123ab8, 0x0, 0x0)
	/app/vendor/github.com/zenhack/go.notmuch/cstruct.go:76 +0xb1 fp=0xc000123a98 sp=0xc000123a60 pc=0x683c31
github.com/zenhack/go%2enotmuch.(*DB).Close(0xc00613a090, 0x1, 0x1)
	/app/vendor/github.com/zenhack/go.notmuch/db.go:41 +0x4e fp=0xc000123ad8 sp=0xc000123a98 pc=0x6850ee
github.com/stbenjam/go-imap-notmuch/pkg/notmuch.(*Mailbox).SearchMessages(0xc0000aca00, 0xc004e0a001, 0xc0000c8120, 0xc0041ac000, 0x1770, 0x1aa0, 0x0, 0x0)
	/app/pkg/notmuch/mailbox.go:188 +0x605 fp=0xc000123c80 sp=0xc000123ad8 pc=0x695f45
github.com/emersion/go-imap/server.(*Search).handle(0xc0000a8030, 0x411201, 0x793268, 0xc000e7c1e0, 0xc0000a8001, 0x7f0f0200efb8)
	/app/vendor/github.com/emersion/go-imap/server/cmd_selected.go:135 +0x6f fp=0xc000123ce8 sp=0xc000123c80 pc=0x6a9b8f
github.com/emersion/go-imap/server.(*Search).UidHandle(0xc0000a8030, 0x793268, 0xc000e7c1e0, 0x7f0f0200efb8, 0xc0000a8030)
	/app/vendor/github.com/emersion/go-imap/server/cmd_selected.go:149 +0x45 fp=0xc000123d28 sp=0xc000123ce8 pc=0x6a9d65
github.com/emersion/go-imap/server.(*Uid).Handle(0xc00612e070, 0x793268, 0xc000e7c1e0, 0xc00612e070, 0x0)
	/app/vendor/github.com/emersion/go-imap/server/cmd_selected.go:338 +0xc4 fp=0xc000123d90 sp=0xc000123d28 pc=0x6aae04
github.com/emersion/go-imap/server.(*conn).handleCommand(0xc000e7c1e0, 0xc000123ed8, 0x6, 0x8, 0x0, 0x0, 0x0)
	/app/vendor/github.com/emersion/go-imap/server/conn.go:397 +0x9e fp=0xc000123e10 sp=0xc000123d90 pc=0x6ad5de
github.com/emersion/go-imap/server.(*conn).serve(0xc000e7c1e0, 0x793268, 0xc000e7c1e0, 0x0, 0x0)
	/app/vendor/github.com/emersion/go-imap/server/conn.go:346 +0x792 fp=0xc000123f48 sp=0xc000123e10 pc=0x6ad0f2
github.com/emersion/go-imap/server.(*Server).serveConn(0xc0000f80b0, 0x793268, 0xc000e7c1e0, 0x0, 0x0)
	/app/vendor/github.com/emersion/go-imap/server/server.go:280 +0xf4 fp=0xc000123fb8 sp=0xc000123f48 pc=0x6aeb34
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc000123fc0 sp=0xc000123fb8 pc=0x470641
created by github.com/emersion/go-imap/server.(*Server).Serve
	/app/vendor/github.com/emersion/go-imap/server/server.go:228 +0x1f4

goroutine 1 [IO wait]:
internal/poll.runtime_pollWait(0x7f0f032a3f18, 0x72, 0x0)
	/usr/lib/golang/src/runtime/netpoll.go:227 +0x55
internal/poll.(*pollDesc).wait(0xc0000ea398, 0x72, 0x0, 0x0, 0x7319e9)
	/usr/lib/golang/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/lib/golang/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc0000ea380, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/internal/poll/fd_unix.go:401 +0x212
net.(*netFD).accept(0xc0000ea380, 0x6ab21f, 0x8, 0x7453e0)
	/usr/lib/golang/src/net/fd_unix.go:172 +0x45
net.(*TCPListener).accept(0xc0000a8888, 0xc0001adcc0, 0xc0001adcc8, 0x28)
	/usr/lib/golang/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc0000a8888, 0x7453d8, 0xc0000f80b0, 0x793268, 0xc00489d380)
	/usr/lib/golang/src/net/tcpsock.go:261 +0x65
github.com/emersion/go-imap/server.(*Server).Serve(0xc0000f80b0, 0x7902c8, 0xc0000a8888, 0x0, 0x0)
	/app/vendor/github.com/emersion/go-imap/server/server.go:216 +0x20e
github.com/emersion/go-imap/server.(*Server).ListenAndServe(0xc0000f80b0, 0xc0000bb130, 0xc0000baa00)
	/app/vendor/github.com/emersion/go-imap/server/server.go:247 +0xb0
main.main()
	/app/main.go:66 +0x1b1

goroutine 25782 [select]:
github.com/emersion/go-imap/server.(*conn).send(0xc000e7c1e0)
	/app/vendor/github.com/emersion/go-imap/server/conn.go:217 +0xd7
created by github.com/emersion/go-imap/server.newConn
	/app/vendor/github.com/emersion/go-imap/server/conn.go:111 +0x27f

goroutine 25785 [runnable]:
github.com/zenhack/go%2enotmuch.(*Messages).Next.func1(0xc000783ad0)
	/app/vendor/github.com/zenhack/go.notmuch/messages.go:36 +0x68
github.com/zenhack/go%2enotmuch.(*Messages).Next(0xc000783ad0, 0xc00011fb78, 0xc003911f40)
	/app/vendor/github.com/zenhack/go.notmuch/messages.go:36 +0x6b
github.com/stbenjam/go-imap-notmuch/pkg/notmuch.(*Mailbox).SearchMessages(0xc0000ac820, 0xc004e0a301, 0xc000ee2120, 0x0, 0x0, 0x0, 0x0, 0x0)
	/app/pkg/notmuch/mailbox.go:167 +0x305
github.com/emersion/go-imap/server.(*Search).handle(0xc00000e288, 0x411201, 0x793268, 0xc00489d380, 0xc00000e201, 0x7f0f0200efb8)
	/app/vendor/github.com/emersion/go-imap/server/cmd_selected.go:135 +0x6f
github.com/emersion/go-imap/server.(*Search).UidHandle(0xc00000e288, 0x793268, 0xc00489d380, 0x7f0f0200efb8, 0xc00000e288)
	/app/vendor/github.com/emersion/go-imap/server/cmd_selected.go:149 +0x45
github.com/emersion/go-imap/server.(*Uid).Handle(0xc00047cd90, 0x793268, 0xc00489d380, 0xc00047cd90, 0x0)
	/app/vendor/github.com/emersion/go-imap/server/cmd_selected.go:338 +0xc4
github.com/emersion/go-imap/server.(*conn).handleCommand(0xc00489d380, 0xc00011fed8, 0x6, 0x8, 0x0, 0x0, 0x0)
	/app/vendor/github.com/emersion/go-imap/server/conn.go:397 +0x9e
github.com/emersion/go-imap/server.(*conn).serve(0xc00489d380, 0x793268, 0xc00489d380, 0x0, 0x0)
	/app/vendor/github.com/emersion/go-imap/server/conn.go:346 +0x792
github.com/emersion/go-imap/server.(*Server).serveConn(0xc0000f80b0, 0x793268, 0xc00489d380, 0x0, 0x0)
	/app/vendor/github.com/emersion/go-imap/server/server.go:280 +0xf4
created by github.com/emersion/go-imap/server.(*Server).Serve
	/app/vendor/github.com/emersion/go-imap/server/server.go:228 +0x1f4

goroutine 25784 [select]:
github.com/emersion/go-imap/server.(*conn).send(0xc00489d380)
	/app/vendor/github.com/emersion/go-imap/server/conn.go:217 +0xd7
created by github.com/emersion/go-imap/server.newConn
	/app/vendor/github.com/emersion/go-imap/server/conn.go:111 +0x27f
```
